# Generated by Django 3.0.7 on 2021-03-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210310_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('MUV', 'MUV'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('VAN', 'VAN'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep'), ('MotorHome', 'MotorHome')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
    ]
