# Generated by Django 3.0.7 on 2021-03-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20210310_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('more then 5', 'more then 5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('More then 10', 'More then 10')]),
        ),
    ]
